// File: alu.v
// Generated by MyHDL 0.11.51
// Date:    Sun May  3 13:24:54 2026 UTC


`timescale 1ns/10ps

module alu (
    data_in_1,
    data_in_2,
    carry_in,
    operation_result,
    carry_out,
    clock_signal,
    opcode,
    negative_flag,
    zero_flag,
    overflow_flag
);


input [7:0] data_in_1;
input [7:0] data_in_2;
input carry_in;
output [7:0] operation_result;
reg [7:0] operation_result;
output carry_out;
reg carry_out;
input clock_signal;
input [3:0] opcode;
output negative_flag;
wire negative_flag;
output zero_flag;
wire zero_flag;
output overflow_flag;
reg overflow_flag;

reg [7:0] accumulate;
reg comb_carry;
reg comb_overflow;
reg [7:0] comb_result;
reg [3:0] count;
reg [7:0] divisor;
reg [7:0] multiplicand;
reg [7:0] multiplier;
reg [7:0] remainder;
reg seq_overflow;
reg [7:0] seq_result;
reg [0:0] state;



always @(data_in_1, opcode, data_in_2, carry_in) begin: comb_logic
    integer total;
    integer diff;
    comb_result = 0;
    comb_carry = 0;
    comb_overflow = 0;
    case (opcode)
        4'b0000: begin
            total = ((data_in_1 + data_in_2) + carry_in);
            comb_result = (total & 255);
            comb_carry = ($signed(total >>> 8) & 1);
            comb_overflow = ((data_in_1[(8 - 1)] == data_in_2[(8 - 1)]) && ((($signed(total >>> (8 - 1)) & 1) != 0) != (data_in_1[(8 - 1)] != 0)));
        end
        4'b0001: begin
            diff = (($signed({1'b0, data_in_1}) - $signed({1'b0, data_in_2})) & ((1 << (8 + 1)) - 1));
            comb_result = (diff & 255);
            comb_carry = ($signed(diff >>> 8) & 1);
            comb_overflow = ((data_in_1[(8 - 1)] != data_in_2[(8 - 1)]) && ((($signed(diff >>> (8 - 1)) & 1) != 0) != (data_in_1[(8 - 1)] != 0)));
        end
        4'b0010: begin
            comb_result = ((data_in_1 | data_in_2) & 255);
        end
        4'b0011: begin
            comb_result = ((~(data_in_1 | data_in_2)) & 255);
        end
        4'b0100: begin
            comb_result = ((data_in_1 & data_in_2) & 255);
        end
        4'b0101: begin
            comb_result = ((~(data_in_1 & data_in_2)) & 255);
        end
        4'b0110: begin
            comb_result = ((data_in_1 ^ data_in_2) & 255);
        end
        4'b0111: begin
            comb_result = ((~(data_in_1 ^ data_in_2)) & 255);
        end
    endcase
end


always @(posedge clock_signal) begin: seq_logic
    integer accumulate_val;
    integer multiplicand_val;
    integer multiplier_val;
    integer partial;
    integer half;
    integer remainder_val;
    integer divisor_val;
    integer partial_r;
    integer quotient;
    reg q_bit;
    integer res;
    case (state)
        1'b0: begin
            case (opcode)
                4'b1000: begin
                    accumulate <= 0;
                    multiplicand <= data_in_1;
                    multiplier <= data_in_2;
                    count <= 0;
                    seq_overflow <= 0;
                    state <= 1'b1;
                end
                4'b1001: begin
                    if ((data_in_2 != 0)) begin
                        remainder <= data_in_1;
                        divisor <= data_in_2;
                        count <= 0;
                        seq_overflow <= 0;
                        state <= 1'b1;
                    end
                    else begin
                        seq_result <= 255;
                        seq_overflow <= 1;
                    end
                end
            endcase
        end
        1'b1: begin
            case (opcode)
                4'b1000: begin
                    if ((count < 8)) begin
                        accumulate_val = accumulate;
                        multiplicand_val = multiplicand;
                        multiplier_val = multiplier;
                        partial = accumulate_val;
                        if ((multiplier_val & 1)) begin
                            partial = (accumulate_val + multiplicand_val);
                        end
                        accumulate <= (partial & 255);
                        multiplicand <= ((multiplicand_val << 1) & 255);
                        multiplier <= $signed(multiplier_val >>> 1);
                        count <= (count + 1);
                        if (($signed({1'b0, count}) == (8 - 1))) begin
                            seq_result <= (partial & 255);
                            seq_overflow <= (partial > 255) ? 1 : 0;
                            state <= 1'b0;
                        end
                    end
                end
                4'b1001: begin
                    if ((count < 8)) begin
                        half = (8 / 2);
                        remainder_val = remainder;
                        divisor_val = divisor;
                        partial_r = ($signed(remainder_val >>> half) & 255);
                        quotient = (remainder_val & ((1 << half) - 1));
                        partial_r = (((partial_r << 1) | ($signed(quotient >>> (half - 1)) & 1)) & 255);
                        q_bit = 0;
                        if ((partial_r >= divisor_val)) begin
                            partial_r = partial_r - divisor_val;
                            q_bit = 1;
                        end
                        remainder <= (((((partial_r & ((1 << half) - 1)) << half) | ((quotient << 1) & ((1 << half) - 1))) | q_bit) & 255);
                        count <= (count + 1);
                        if (($signed({1'b0, count}) == (8 - 1))) begin
                            res = (((((partial_r & ((1 << half) - 1)) << half) | ((quotient << 1) & ((1 << half) - 1))) | q_bit) & 255);
                            seq_result <= (res & ((1 << half) - 1));
                            seq_overflow <= 0;
                            state <= 1'b0;
                        end
                    end
                end
                default: begin
                    state <= 1'b0;
                end
            endcase
        end
    endcase
end


always @(seq_result, comb_result, opcode, comb_carry, seq_overflow, comb_overflow) begin: out_mux
    if (((opcode == 4'b1000) || (opcode == 4'b1001))) begin
        operation_result = seq_result;
        overflow_flag = seq_overflow;
        carry_out = 1'b0;
    end
    else begin
        operation_result = comb_result;
        overflow_flag = comb_overflow;
        carry_out = comb_carry;
    end
end



assign zero_flag = (operation_result == 0);
assign negative_flag = operation_result[(8 - 1)];

endmodule
